services:
  frontend:
    container_name: test-frontend
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front/logs:/var/log/nginx
      - ./front/certs:/etc/nginx/certs:ro
      - ./admin:/app/admin
    links:
      - api
      - site
      - postgres

  admin:
    container_name: test-admin
    image: node:24
    working_dir: /app
    command: npm run build
    volumes:
      - ./admin:/app

  postgres:
    container_name: test-database
    image: postgres:18.0
    restart: always
    environment:
      POSTGRES_DB: api_development
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ./data/postgres:/var/lib/postgresql/data

  api:
    container_name: test-api
    build: api/.
#    image: ruby:slim-trixie
    working_dir: /app
    command: bash start.sh
    depends_on:
      - postgres
    volumes:
      - ./api:/app
    links:
      - postgres
    ports:
      - "3030:3000"


  site:
    container_name: test-site
    image: node:24
    working_dir: /app
    command: bash start.sh
    ports:
      - "3010:3000"
    volumes:
      - ./site:/app
    links:
      - api