
default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_development
  host: localhost

test:
  <<: *default
  database: api_test
  host: postgres

production:
  <<: *default
  database: api_development
  host: postgres
